/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ball.gltf
Author: Tommyleenev (https://sketchfab.com/tommyleenev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/beach-ball-free-download-c915a99e9bae4dbe8dd7be3215e19ba0
Title: Beach Ball (Free Download)
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Ball(props) {
  const { nodes, materials } = useGLTF("/3dmodels/ball/ball.gltf");
  const ref = useRef();

  useFrame(() => {
    if (!ref.current) return;
    ref.current.rotation.x -= 0.005;
    ref.current.rotation.y += 0.001;
    ref.current.rotation.z += 0.01;
  });
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere_0.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[0, 1, 10]}
      />
    </group>
  );
}

useGLTF.preload("/3dmodels/ball/ball.gltf");
