/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 coffee_mug.gltf
Author: The Lister (https://sketchfab.com/MortemNightshade)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-mug-6c95897de04143aeb5c75b7630707d27
Title: Coffee Mug
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function CoffeeMug(props) {
  const { nodes, materials } = useGLTF("/3dmodels/coffee_mug/coffee_mug.gltf");

  const ref = useRef();

  useFrame(() => {
    if (!ref.current) return;
    ref.current.rotation.x -= 0.005;
    ref.current.rotation.y += 0.001;
    ref.current.rotation.z -= 0.01;
  });
  return (
    <group ref={ref} {...props} dispose={null}>
      <group
        position={[6, -1, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.1}
      >
        <mesh
          geometry={nodes.Mug_M_Mug_0.geometry}
          material={materials.M_Mug}
          rotation={[-Math.PI, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3dmodels/coffee_mug/coffee_mug.gltf");
