/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 croissant.gltf
Author: chaeseoyeong (https://sketchfab.com/chaeseoyeong)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/croissant-352b485c757f48c19a45a30ac0077489
Title: Croissant
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { degreesToRadians } from "popmotion";
import { useRef } from "react";

export function Croissant(props) {
  const { nodes, materials } = useGLTF("/3dmodels/croissant/croissant.gltf");
  const ref = useRef();

  useFrame(() => {
    if (!ref.current) return;
    ref.current.rotation.x += 0.01;
    ref.current.rotation.y += 0.001;
  });
  return (
    <group ref={ref} {...props} dispose={null}>
      <group
        rotation={[
          degreesToRadians(180),
          degreesToRadians(180),
          degreesToRadians(180),
        ]}
        position={[0.001, 0, -0.01]}
      >
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            geometry={nodes.Model_material0_0.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_1.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material0_0_2.geometry}
            material={materials.material0}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3dmodels/croissant/croissant.gltf");
