/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 lego_block.gltf
Author: Joebuz33 (https://sketchfab.com/Joebuz33)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lego-block-2x4-1985-d9db0ec3cffb4c3a99a4b71b2644b586
Title: LEGO block 2x4 (1985 +)
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function LegoBlock(props) {
  const { nodes, materials } = useGLTF("/3dmodels/lego_block/lego_block.gltf");

  const ref = useRef();

  useFrame(() => {
    if (!ref.current) return;
    ref.current.rotation.x -= 0.005;
    ref.current.rotation.y += 0.001;
    ref.current.rotation.z -= 0.01;
  });

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Material}
        scale={[0.17, 0.85, 1.98]}
        position={[1, 10, 10]}
      />
    </group>
  );
}

useGLTF.preload("/3dmodels/lego_block/lego_block.gltf");
