/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 luggage.gltf
Author: KoteTheCat (https://sketchfab.com/KoteTheCat)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/week-15-luggage-bake-v2-cd4dba634164441f850f42933885ea71
Title: Week 15 - Luggage Bake V2
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useEffect, useRef, useState } from "react";

export function Luggage(props) {
  const [clicked, setClicked] = useState(false);
  const { nodes, materials } = useGLTF("3dmodels/luggage/luggage.gltf");

  const ref = useRef();

  useFrame(() => {
    if (!ref.current || clicked) return;
    ref.current.rotation.x += 0.001;
    ref.current.rotation.y += 0.01;
    ref.current.rotation.z += 0.002;
  });

  return (
    <group
      ref={ref}
      {...props}
      dispose={null}
      onClick={(e) => {
        e.stopPropagation();
        setClicked((prev) => !prev);
      }}
    >
      <group position={[0, 0, -5]}>
        <mesh
          geometry={nodes.luggage_1_low_luggage_HP_v2plastic_black_0.geometry}
          material={materials.luggage_HP_v2plastic_black}
        />
        <mesh
          geometry={nodes.luggage_1_low_luggage_HP_v2black_cloth2_0.geometry}
          material={materials.luggage_HP_v2black_cloth2}
        />
        <mesh
          geometry={nodes.luggage_1_low_luggage_HP_v2black_cloth_0.geometry}
          material={materials.luggage_HP_v2black_cloth}
        />
      </group>
      <group position={[0, 0, -5]}>
        <mesh
          geometry={nodes.luggage_2_low_luggage_HP_v2metal_0.geometry}
          material={materials.luggage_HP_v2metal}
        />
        <mesh
          geometry={nodes.luggage_2_low_luggage_HP_v2green_plastic_0.geometry}
          material={materials.luggage_HP_v2green_plastic}
        />
        <mesh
          geometry={nodes.luggage_2_low_luggage_HP_v2plastic_old_0.geometry}
          material={materials.luggage_HP_v2plastic_old}
        />
        <mesh
          geometry={nodes.luggage_2_low_luggage_HP_v2plastic_black_0.geometry}
          material={materials.luggage_HP_v2plastic_black}
        />
        <mesh
          geometry={nodes.luggage_2_low_luggage_HP_v2check_0.geometry}
          material={materials.luggage_HP_v2check}
        />
      </group>
      <group position={[0, 0, -5]}>
        <mesh
          geometry={nodes.luggage_3_low_luggage_HP_v2check_0.geometry}
          material={materials.luggage_HP_v2check}
        />
        <mesh
          geometry={nodes.luggage_3_low_luggage_HP_v2black_cloth_0.geometry}
          material={materials.luggage_HP_v2black_cloth}
        />
      </group>
      <mesh
        geometry={nodes.luggage_4_low_luggage_HP_v2plastic_black_0.geometry}
        material={materials.luggage_HP_v2plastic_black}
      />
      <mesh
        geometry={nodes.luggage_4_low_luggage_HP_v2check_0.geometry}
        material={materials.luggage_HP_v2check}
      />
      <mesh
        geometry={
          nodes.luggage_4_low_luggage_HP_v2bright_green_plastic_0.geometry
        }
        material={materials.luggage_HP_v2bright_green_plastic}
      />
      <mesh
        geometry={nodes.luggage_5_low_luggage_HP_v2plastic_black_0.geometry}
        material={materials.luggage_HP_v2plastic_black}
      />
    </group>
  );
}

useGLTF.preload("3dmodels/luggage/luggage.gltf");
