/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 strawberry.gltf
Author: gelmi.com.br (https://sketchfab.com/rodrigogelmi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/strawberry-dd6a424807614544835c8cc4529d6f0d
Title: Strawberry
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { degreesToRadians } from "popmotion";

export function Strawberry(props) {
  const { nodes, materials } = useGLTF("3dmodels/strawberry/strawberry.gltf");
  const ref = useRef();

  useFrame(() => {
    if (!ref.current) return;
    ref.current.rotation.x -= 0.001;
    ref.current.rotation.y += 0.01;
    ref.current.rotation.z -= 0.001;
  });

  return (
    <group ref={ref} {...props} dispose={null}>
      <group
        position={[0, 1, -0.11]}
        rotation={[degreesToRadians(90), degreesToRadians(90), 0]}
        scale={0.08}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.MORANGO}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.MORANGO}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.MORANGO}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("3dmodels/strawberry/strawberry.gltf");
